version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9005:9000"
      - "9006:9001" 
    environment:
      MINIO_ROOT_USER: nikola
      MINIO_ROOT_PASSWORD: nikolanikola
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  nifi:
    image: apache/nifi:2.6.0
    container_name: nifi
    ports:
      - "8443:8443"
    environment:
      - NIFI_WEB_HTTP_PORT=8443
      - SINGLE_USER_CREDENTIALS_USERNAME=nikola
      - SINGLE_USER_CREDENTIALS_PASSWORD=nikolanikola
    depends_on:
      - minio
    volumes:
      - nifi_content_repository:/opt/nifi/nifi-current/content_repository
      - nifi_database_repository:/opt/nifi/nifi-current/database_repository
      - nifi_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi_provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi_logs:/opt/nifi/nifi-current/logs
      - nifi_state:/opt/nifi/nifi-current/state
      - nifi_conf:/opt/nifi/nifi-current/conf

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeperlog_data:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092   #na 9092  se povezuje python ili bilo sta spoljasnje
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:19092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  spark-master-stream:
    image: apache/spark:3.5.0
    container_name: spark-master-stream
    ports:
      - "9090:8080"
      - "7077:7077"
    command: ["/bin/bash", "-c", "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master -h 0.0.0.0"]

  spark-worker-stream:
    image: apache/spark:3.5.0
    container_name: spark-worker-stream
    depends_on:
      - spark-master-stream
    command: ["/bin/bash", "-c", "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master-stream:7077"]

  spark-master-batch:
    image: apache/spark:3.5.0
    container_name: spark-master-batch
    ports:
      - "9091:8080"
      - "7078:7077"
    command: ["/bin/bash", "-c", "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master -h 0.0.0.0"]

  spark-worker-batch:
    image: apache/spark:3.5.0
    container_name: spark-worker-batch
    depends_on:
      - spark-master-batch
    command: ["/bin/bash", "-c", "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master-batch:7077"]

  postgres: 
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres1
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  streamyt:
    build:
      context: .
      dockerfile: dockerfile-stream
    depends_on:
      - spark-master-stream
      - spark-worker-stream
      - kafka
      - kafka-ui
    environment:
      - SPARK_MASTER_URL=spark://spark-master-stream:7077

  batchyt:
    build:
      context: .
      dockerfile: dockerfile-batch
    depends_on:
      - spark-master-batch
      - spark-worker-batch
      - minio
      - postgres
    environment:
      - SPARK_MASTER_URL=spark://spark-master-batch:7077

  # metabase:
  #   image: metabase/metabase:latest
  #   container_name: metabase
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     MB_DB_TYPE: postgres
  #     MB_DB_DBNAME: postgres1
  #     MB_DB_PORT: 5432
  #     MB_DB_USER: postgres
  #     MB_DB_PASS: postgres
  #     MB_DB_HOST: postgres
  #   depends_on:
  #     - postgres
      
volumes:
  minio_data:
    name: minio_data
  nifi_content_repository:
    name: nifi_content_repository
  nifi_database_repository:
    name: nifi_database_repository
  nifi_flowfile_repository:
    name: nifi_flowfile_repository
  nifi_provenance_repository:
    name: nifi_provenance_repository
  nifi_logs:
    name: nifi_logs
  nifi_state:
    name: nifi_state
  nifi_conf:
    name: nifi_conf
  zookeeper_data:
    name: zookeeper_data
  zookeeperlog_data:
    name: zookeeperlog_data
  kafka_data:
    name: kafka_data
